refs #5472 Filesystems filling up with postgres backup files

diff --git a/usr/share/metacat/debian/pgsql-daily b/usr/share/metacat/debian/pgsql-daily
--- a/usr/share/metacat/debian/pgsql-daily
+++ b/usr/share/metacat/debian/pgsql-daily
@@ -1,4 +1,5 @@
 #!/bin/bash
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
 DUMP_DATE=$(date +%F-%H%M);
 DUMP_CMD="/usr/bin/pg_dump";
 DUMP_OPTS="-Fc";
@@ -8,21 +9,48 @@ DUMP_DIR_MONTHS="/var/postgres-bak/months";
 DUMP_DIR="/var/postgres-bak/";
 DUMP_FILE="metacatDB.${DUMP_DATE}.dump";
 DUMP_ERR="metacatDB.${DUMP_DATE}.err";
+DUMP_LOG="/var/log/dataone/pgsql-daily-dump.log"
+function log() 
+{
+	#
+	# Set Up logging
+	# Reminder: don't echo to stdout, it messes up debconf
+	#
+    now=$(date "+%Y-%m-%d %H:%M:%S %Z: ")
+    echo -e "${now} crontab pgsql daily $@" >> ${DUMP_LOG}
+}
+log "starting"
 
 if [[ ! -d ${DUMP_DIR} ]]; then
-    mkdir ${DUMP_DIR};
-    chown -R postgres ${DUMP_DIR};
+  if ! (/bin/mkdir ${DUMP_DIR} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/mkdir ${DUMP_DIR} failed"
+  fi
+  if ! (/bin/chown -R postgres ${DUMP_DIR} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/chown -R postgres ${DUMP_DIR}"
+  fi
 fi
 
 if [[ ! -d ${DUMP_DIR_MONTHS} ]]; then
-    mkdir ${DUMP_DIR_MONTHS};
-    chown -R postgres ${DUMP_DIR_MONTHS};
+
+  if ! (/bin/mkdir ${DUMP_DIR_MONTHS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/mkdir ${DUMP_DIR_MONTHS}"
+  fi
+
+  if ! (/bin/chown -R postgres ${DUMP_DIR_MONTHS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/chown -R postgres ${DUMP_DIR_MONTHS}"
+  fi
+
 fi
 
-
-find ${DUMP_DIR} -daystart -mtime +31 -regextype posix-extended  -regex '${DUMP_DIR}metacatDB.[0-9]{4}.[0-9]{2}.01.[0-9]{4}.(dump|err)' -exec mv {} ${DUMP_DIR_MONTHS} \;
-
-find ${DUMP_DIR} -daystart -mtime +32 -regextype posix-extended  -regex '${DUMP_DIR}metacatDB.[0-9]{4}.[0-9]{2}.[0-9]{2}.[0-9]{4}.err' -exec rm {} \;
+if ! (/usr/bin/find ${DUMP_DIR} -daystart -mtime +31 -regextype posix-extended  -regex "${DUMP_DIR}metacatDB.[0-9]{4}.[0-9]{2}.01.[0-9]{4}.(dump|err)" -exec /bin/mv {} ${DUMP_DIR_MONTHS} \; >> ${DUMP_LOG} 2>&1); then
+  log "unable to find and move monthly dumps"
+else
+  log "found and moved monthly dumps if there were any"
+  if ! (/usr/bin/find ${DUMP_DIR} -daystart -mtime +32 -regextype posix-extended  -regex "${DUMP_DIR}metacatDB.[0-9]{4}.[0-9]{2}.[0-9]{2}.[0-9]{4}.(dump|err)" -exec /bin/rm {} \; >> ${DUMP_LOG} 2>&1); then
+    log "unable to remove daily dump files"
+  fi
+fi
 
 nohup su postgres -c "${DUMP_CMD} ${DUMP_OPTS} ${DUMP_DB}" > ${DUMP_DIR}${DUMP_FILE} 2> ${DUMP_DIR}${DUMP_ERR} < /dev/null &
 
+log "completed"
diff --git a/usr/share/metacat/debian/pgsql-monthly b/usr/share/metacat/debian/pgsql-monthly
--- a/usr/share/metacat/debian/pgsql-monthly
+++ b/usr/share/metacat/debian/pgsql-monthly
@@ -1,18 +1,43 @@
 #!/bin/bash
-
 DUMP_DIR_MONTHS="/var/postgres-bak/months";
 DUMP_DIR_YEARS="/var/postgres-bak/years";
+DUMP_LOG="/var/log/dataone/pgsql-monthly-dump.log"
+function log()
+{
+        #
+        # Set Up logging
+        # Reminder: don't echo to stdout, it messes up debconf
+        #
+    now=$(date "+%Y-%m-%d %H:%M:%S %Z: ")
+    echo -e "${now} crontab pgsql monthly $@" >> ${DUMP_LOG}
+}
+log "starting"
 
 if [[ ! -d ${DUMP_DIR_MONTHS} ]]; then
-    mkdir ${DUMP_DIR_MONTHS};
-    chown -R postgres ${DUMP_DIR_MONTHS};
+  if ! (/bin/mkdir ${DUMP_DIR_MONTHS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/mkdir ${DUMP_DIR_MONTHS} failed"
+  fi
+  if ! (/bin/chown -R postgres ${DUMP_DIR_MONTHS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/chown -R postgres ${DUMP_DIR_MONTHS}"
+  fi
 fi
 
 if [[ ! -d ${DUMP_DIR_YEARS} ]]; then
-    mkdir ${DUMP_DIR_YEARS};
-    chown -R postgres ${DUMP_DIR_YEARS};
+  if ! (/bin/mkdir ${DUMP_DIR_YEARS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/mkdir ${DUMP_DIR_YEARS} failed"
+  fi
+  if ! (/bin/chown -R postgres ${DUMP_DIR_YEARS} >> ${DUMP_LOG} 2>&1); then
+    log "/bin/chown -R postgres ${DUMP_DIR_YEARS}"
+  fi
 fi
 
-find ${DUMP_DIR_MONTHS} -daystart -mtime +366 -regextype posix-extended  -regex '${DUMP_DIR_MONTHS}metacatDB.[0-9]{4}.01.01.[0-9]{4}.(dump|err)' -exec mv {} ${DUMP_DIR_YEARS} \;
+if ! (/usr/bin/find ${DUMP_DIR_MONTHS} -daystart -mtime +366 -regextype posix-extended  -regex "${DUMP_DIR_MONTHS}metacatDB.[0-9]{4}.01.01.[0-9]{4}.(dump|err)" -exec /bin/mv {} ${DUMP_DIR_YEARS} \; >> ${DUMP_LOG} 2>&1); then
+  log "unable to find and move yearly dump"
+else
+  log "found and moved yearly dumps if there were any"
+  if ! (/usr/bin/find ${DUMP_DIR_MONTHS} -daystart -mtime +397 -regextype posix-extended  -regex "${DUMP_DIR_MONTHS}metacatDB.[0-9]{4}.[0-9]{2}.[0-9]{2}.[0-9]{4}.err"  -exec /bin/rm {} \; >> ${DUMP_LOG} 2>&1); then
+    log "unable to remove monthly dump files"
+  fi
+fi
 
-find ${DUMP_DIR_MONTHS} -daystart -mtime +397 -regextype posix-extended  -regex '${DUMP_DIR_MONTHS}metacatDB.[0-9]{4}.[0-9]{2}.[0-9]{2}.[0-9]{4}.err'  -exec rm {} \;
+log "completed"
